services:
  - type: web
    name: tunag-lite-frontend
    runtime: docker
    region: singapore
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_API_PORT
        fromService:
          type: pserv
          name: tunag-lite-backend
          property: hostport

  - type: pserv
    name: tunag-lite-backend
    runtime: docker
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: air-hockey-db
          property: connectionString
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: APP_HOSTS
        value: "*"


    plan: free
    region: singapore
    databaseName: tunaglite
    user: tunaglite
