services:
  - type: web
    name: tunag-lite-frontend
    runtime: docker
    region: singapore
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    healthCheckPath: /
    envVars:
      - key: BACKEND_BASE_URL
        value: https://tunag-lite-backend.onrender.com
      - key: RENDER_EXTERNAL_URL
        value: https://tunag-lite-frontend.onrender.com

  - type: web
    name: tunag-lite-backend
    runtime: docker
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: APP_HOSTS
        value: "*"
