services:
  - type: web
    name: tunag-lite-frontend
    runtime: docker
    region: singapore
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    healthCheckPath: /api/posts
    envVars:
      - key: BACKEND_HOSTPORT
        fromService:
          type: web
          name: tunag-lite-backend
          property: hostport
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: tunag-lite-frontend
          property: host

  - type: web
    name: tunag-lite-backend
    runtime: docker
    region: singapore
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: APP_HOSTS
        value: "*"
